"""
Test suite for tool2_tech_docs.py

What is tested:
    - generate_docs(): orchestrates file fetching and Claude calls
    - build_index(): constructs markdown index from doc dict
    - __main__ block behaviour (happy path, exception path)
    - fmt() inner function behaviour (via generate_docs side-effects)
    - Edge cases: empty file dicts, missing env vars, Claude failures

Mocks used:
    - shared.call_claude          → unittest.mock.MagicMock / patch
    - shared.get_repo_files       → unittest.mock.patch
    - shared.write_output_file    → unittest.mock.patch
    - shared.send_email           → unittest.mock.patch
    - shared.email_html           → unittest.mock.patch
    - shared.write_audit_entry    → unittest.mock.patch
    - shared.OUTPUT_REPO_OWNER    → patched as module attribute
    - shared.OUTPUT_REPO          → patched as module attribute
    - datetime.datetime.utcnow    → patched for deterministic timestamps

TODOs:
    - TODO: Integration test with a real (sandboxed) Claude API call
    - TODO: Test write_output_file network failures with retries if applicable
    - TODO: Verify exact Claude prompt content once prompt format is stabilised
"""

import sys
import os
import importlib
import types
import datetime
from unittest import mock
from unittest.mock import MagicMock, patch, call

import pytest

# ---------------------------------------------------------------------------
# Helpers to import the module under test with all shared dependencies mocked
# ---------------------------------------------------------------------------

SHARED_MODULE_PATH = "shared"  # as inserted into sys.path by tool2_tech_docs.py


def _make_shared_mock():
    """Return a mock module that satisfies every name imported from shared."""
    m = types.ModuleType("shared")
    m.call_claude = MagicMock(return_value="generated content")
    m.get_repo_files = MagicMock(return_value={})
    m.write_output_file = MagicMock(return_value="https://github.com/out/repo/blob/main/file")
    m.send_email = MagicMock()
    m.email_html = MagicMock(return_value="<html>body</html>")
    m.write_audit_entry = MagicMock()
    m.OUTPUT_REPO_OWNER = "test-output-owner"
    m.OUTPUT_REPO = "test-output-repo"
    return m


@pytest.fixture()
def shared_mock():
    """Inject a fresh shared mock into sys.modules before each test."""
    m = _make_shared_mock()
    with mock.patch.dict(sys.modules, {"shared": m}):
        yield m


@pytest.fixture()
def tool2(shared_mock):
    """Import (or re-import) the module under test after shared is mocked."""
    # Remove cached version so we get a clean import each time
    sys.modules.pop("tool2_tech_docs", None)
    script_dir = os.path.join(os.path.dirname(__file__), "..", ".github", "scripts")
    script_dir = os.path.abspath(script_dir)
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)
    import tool2_tech_docs as t2
    return t2


# ---------------------------------------------------------------------------
# Tests for build_index()
# ---------------------------------------------------------------------------


class TestBuildIndex:
    def test_happy_path_returns_markdown_with_links(self, tool2, shared_mock):
        docs = {
            "README.md": "readme content",
            "ARCHITECTURE.md": "arch content",
            "RUNBOOK.md": "runbook content",
        }
        result = tool2.build_index("myowner", "myrepo", docs, "2024-01-15 12:00 UTC")

        assert "# Tech Documentation Index — myowner/myrepo" in result
        assert "**Generated:** 2024-01-15 12:00 UTC" in result
        assert "README.md" in result
        assert "ARCHITECTURE.md" in result
        assert "RUNBOOK.md" in result
        assert "_Auto-generated by AI Delivery Bot_" in result

    def test_links_use_output_repo_owner_and_repo(self, tool2, shared_mock):
        docs = {"README.md": "content"}
        result = tool2.build_index("srcowner", "srcrepo", docs, "2024-01-15 12:00 UTC")

        expected_url = (
            "https://github.com/test-output-owner/test-output-repo"
            "/blob/main/tech-docs/srcowner-srcrepo/README.md"
        )
        assert expected_url in result

    def test_empty_docs_produces_valid_index(self, tool2, shared_mock):
        result = tool2.build_index("o", "r", {}, "2024-01-01 00:00 UTC")
        assert "# Tech Documentation Index" in result
        assert "## Documents" in result

    def test_special_characters_in_owner_repo(self, tool2, shared_mock):
        docs = {"README.md": "x"}
        # Should not raise; special chars go into the URL as-is
        result = tool2.build_index("my-org", "my.repo", docs, "2024-01-01 00:00 UTC")
        assert "my-org/my.repo" in result

    def test_multiple_docs_all_appear_as_list_items(self, tool2, shared_mock):
        docs = {
            "README.md": "",
            "ARCHITECTURE.md": "",
            "RUNBOOK.md": "",
        }
        result = tool2.build_index("o", "r", docs, "now")
        for name in docs:
            assert f"- [{name}]" in result

    def test_timestamp_appears_verbatim(self, tool2, shared_mock):
        ts = "2099-12-31 23:59 UTC"
        result = tool2.build_index("o", "r", {}, ts)
        assert ts in result


# ---------------------------------------------------------------------------
# Tests for generate_docs()
# ---------------------------------------------------------------------------


class TestGenerateDocs:
    def test_calls_get_repo_files_twice(self, tool2, shared_mock):
        tool2.generate_docs("owner", "repo", "https://run-url")
        assert shared_mock.get_repo_files.call_count == 2

    def test_first_get_repo_files_fetches_source_extensions(self, tool2, shared_mock):
        tool2.generate_docs("owner", "repo", "https://run-url")
        first_call_args = shared_mock.get_repo_files.call_args_list[0]
        extensions = first_call_args[0][2]  # positional arg index 2
        assert ".py" in extensions
        assert ".js" in extensions
        assert ".ts" in extensions
        assert ".go" in extensions

    def test_second_get_repo_files_fetches_iac_extensions(self, tool2, shared_mock):
        tool2.generate_docs("owner", "repo", "https://run-url")
        second_call_args = shared_mock.get_repo_files.call_args_list[1]
        extensions = second_call_args[0][2]
        assert ".tf" in extensions
        assert ".yaml" in extensions
        assert ".yml" in extensions

    def test_calls_call_claude_three_times(self, tool2, shared_mock):
        tool2.generate_docs("owner", "repo", "https://run-url")
        assert shared_mock.call_claude.call_count == 3

    def test_returns_dict_with_three_docs(self, tool2, shared_mock):
        shared_mock.call_claude.side_effect = ["readme", "arch", "runbook"]
        result = tool2.generate_docs("owner", "repo", "https://run-url")
        assert set(result.keys()) == {"README.md", "ARCHITECTURE.md", "RUNBOOK.md"}

    def test_readme_content_matches_claude_output(self, tool2, shared_mock):
        shared_mock.call_claude.side_effect = ["MY_README", "MY_ARCH", "MY_RUNBOOK"]
        result = tool2.generate_docs("owner", "repo", "https://run-url")
        assert result["README.md"] == "MY_README"

    def test_architecture_content_matches_claude_output(self, tool2, shared_mock):
        shared_mock.call_claude.side_effect = ["r", "MY_ARCH", "rn"]
        result = tool2.generate_docs("owner", "repo", "https://run-url")
        assert result["ARCHITECTURE.md"] == "MY_ARCH"

    def test_runbook_content_matches_claude_output(self, tool2, shared_mock):
        shared_mock.call_claude.side_effect = ["r", "a", "MY_RUNBOOK"]
        result = tool2.generate_docs("owner", "repo", "https://run-url")
        assert result["RUNBOOK.md"] == "MY_RUNBOOK"

    def test_owner_repo_in_readme_prompt(self, tool2, shared_mock):
        tool2.generate_docs("testowner", "testrepo", "https://run-url")
        readme_call = shared_mock.call_claude.call_args_list[0]
        prompt = readme_call[0][1]
        assert "testowner/testrepo" in prompt

    def test_owner_repo_in_arch_prompt(self, tool2, shared_mock):
        tool2.generate_docs("testowner", "testrepo", "https://run-url")
        arch_call = shared_mock.call_claude.call_args_list[1]
        prompt = arch_call[0][1]
        assert "testowner/testrepo" in prompt

    def test_owner_repo_in_runbook_prompt(self, tool2, shared_mock):
        tool2.generate_docs("testowner", "testrepo", "https://run-url")
        runbook_call = shared_mock.call_claude.call_args_list[2]
        prompt = runbook_call[0][1]
        assert "testowner/testrepo" in prompt

    def test_no_files_produces_no_files_found_placeholder(self, tool2, shared_mock):
        shared_mock.get_repo_files.return_value = {}
        tool2.generate_docs("owner", "repo", "https://run-url")
        # At least one prompt should contain the placeholder
        all_prompts = [c[0][1] for c in shared_mock.call_claude.call_args_list]
        assert any("_No files found_" in p for p in all_prompts)

    def test_files_are_truncated_to_4000_chars(self, tool2, shared_mock):
        long_content = "x" * 10_000
        shared_mock.get_repo_files.return_value = {"bigfile.py": long_content}
        tool2.generate_docs("owner", "repo", "https://run-url")
        # The prompt should contain exactly 4000 x's, not 10000
        readme_prompt = shared_mock.call_claude.call_args_list[0][0][1]
        # The slice [:4000] means at most 4000 chars of content in each block
        assert "x" * 4001 not in readme_prompt
        assert "x" * 4000 in readme_prompt

    def test_claude_exception_propagates(self, tool2, shared_mock):
        shared_mock.call_claude.side_effect = RuntimeError("Claude failed")
        with pytest.raises(RuntimeError, match="Claude failed"):
            tool2.generate_docs("owner", "repo", "https://run-url")

    def test_get_repo_files_called_with_correct_owner_repo(self, tool2, shared_mock):
        tool2.generate_docs("specificowner", "specificrepo", "https://run-url")
        for c in shared_mock.get_repo_files.call_args_list:
            assert c[0][0] == "specificowner"
            assert c[0][1] == "specificrepo"

    def test_max_files_respected_for_source_files(self, tool2, shared_mock):
        tool2.generate_docs("owner", "repo", "https://run-url")
        first_call_kwargs = shared_mock.get_repo_files.call_args_list[0]
        # max_files passed as keyword arg
        assert first_call_kwargs[1].get("max_files") == 15

    def test_max_files_respected_for_iac_files(self, tool2, shared_mock):
        tool2.generate_docs("owner", "repo", "https://run-url")
        second_call_kwargs = shared_mock.get_repo_files.call_args_list[1]
        assert second_call_kwargs[1].get("max_files") == 10

    def test_multiple_files_all_appear_in_prompt(self, tool2, shared_mock):
        shared_mock.get_repo_files.side_effect = [
            {"main.py": "print('hello')", "util.py": "def foo(): pass"},
            {},
        ]
        tool2.generate_docs("owner", "repo", "https://run-url")
        readme_prompt = shared_mock.call_claude.call_args_list[0][0][1]
        assert "main.py" in readme_prompt
        assert "util.py" in readme_prompt


# ---------------------------------------------------------------------------
# Tests for fmt() inner function (tested indirectly via generate_docs)
# ---------------------------------------------------------------------------


class TestFmtInnerFunction:
    def test_single_file_formatted_with_header_and_fence(self, tool2, shared_mock):
        shared_mock.get_repo_files.side_effect = [
            {"somefile.py": "content here"},
            {},
        ]
        tool2.generate_docs("o", "r", "url")
        prompt = shared_mock.call_claude.call_args_list[0][0][1]
        assert "### somefile.py" in prompt
        assert "```" in prompt
        assert "content here" in prompt

    def test_empty_dict_produces_no_files_found(self, tool2, shared_mock):
        shared_mock.get_repo_files.return_value = {}
        tool2.generate_docs("o", "r", "url")
        prompt = shared_mock.call_claude.call_args_list[0][0][1]
        assert "_No files found_" in prompt

    def test_multiple_files_joined_with_double_newline(self, tool2, shared_mock):
        shared_mock.get_repo_files.side_effect = [
            {"a.py": "aaa", "b.py": "bbb"},
            {},
        ]
        tool2.generate_docs("o", "r", "url")
        prompt = shared_mock.call_claude.call_args_list[0][0][1]
        # Both headers should appear with content between them
        a_pos = prompt.index("### a.py")
        b_pos = prompt.index("### b.py")
        assert a_pos != b_pos  # both present


# ---------------------------------------------------------------------------
# Tests for system prompts (constants)
# ---------------------------------------------------------------------------


class TestSystemPrompts:
    def test_system_readme_is_string(self, tool2):
        assert isinstance(tool2.SYSTEM_README, str)
        assert len(tool2.SYSTEM_README) > 0

    def test_system_arch_is_string(self, tool2):
        assert isinstance(tool2.SYSTEM_ARCH, str)
        assert len(tool2.SYSTEM_ARCH) > 0

    def test_system_runbook_is_string(self, tool2):
        assert isinstance(tool2.SYSTEM_RUNBOOK, str)
        assert len(tool2.SYSTEM_RUNBOOK) > 0

    def test_system_readme_contains_required_sections(self, tool2):
        for section in ["README", "Tech stack", "Architecture", "Environment variables"]:
            assert section in tool2.