"""
Test suite for tool2_tech_docs.py

What is tested:
  - generate_docs(): orchestration of get_repo_files + call_claude calls
  - build_index(): markdown index generation with correct links, timestamps, doc names
  - __main__ block: happy path execution, exception/failure path (audit + email on error)

Mocks used:
  - shared.call_claude          → unittest.mock.patch
  - shared.get_repo_files       → unittest.mock.patch
  - shared.write_output_file    → unittest.mock.patch
  - shared.send_email           → unittest.mock.patch
  - shared.email_html           → unittest.mock.patch
  - shared.write_audit_entry    → unittest.mock.patch
  - datetime.datetime.utcnow    → unittest.mock.patch
  - os.environ                  → monkeypatch / unittest.mock.patch.dict

TODOs:
  - TODO: Integration test against a real GitHub repo requires credentials — stubbed below
  - TODO: Verify exact Claude prompt content once prompt format is locked
  - TODO: Test behaviour when OUTPUT_REPO_OWNER / OUTPUT_REPO constants change
"""

import importlib
import sys
import os
import types
import datetime
from unittest.mock import patch, MagicMock, call

import pytest

# ---------------------------------------------------------------------------
# Helpers to import the module under test while injecting a fake `shared`
# ---------------------------------------------------------------------------

FAKE_OUTPUT_REPO_OWNER = "test-org"
FAKE_OUTPUT_REPO = "test-output-repo"


def _make_fake_shared():
    """Return a minimal fake `shared` module so tool2_tech_docs can be imported."""
    fake = types.ModuleType("shared")
    fake.call_claude = MagicMock(return_value="# Generated content")
    fake.get_repo_files = MagicMock(return_value={})
    fake.write_output_file = MagicMock(return_value="https://github.com/output/file")
    fake.send_email = MagicMock()
    fake.email_html = MagicMock(return_value="<html>body</html>")
    fake.write_audit_entry = MagicMock()
    fake.OUTPUT_REPO_OWNER = FAKE_OUTPUT_REPO_OWNER
    fake.OUTPUT_REPO = FAKE_OUTPUT_REPO
    return fake


@pytest.fixture(autouse=True)
def inject_fake_shared():
    """Ensure a fresh fake shared module is injected before every test."""
    fake_shared = _make_fake_shared()
    with patch.dict(sys.modules, {"shared": fake_shared}):
        # Remove cached tool2_tech_docs so it re-imports with the fresh fake
        sys.modules.pop("tool2_tech_docs", None)
        yield fake_shared
    sys.modules.pop("tool2_tech_docs", None)


def import_module():
    """Import (or re-import) tool2_tech_docs after shared is patched."""
    import tool2_tech_docs as m
    return m


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

SAMPLE_PY_FILES = {
    "src/main.py": "print('hello')" * 10,
    "src/utils.py": "def helper(): pass",
}

SAMPLE_IAC_FILES = {
    "infra/main.tf": 'resource "aws_s3_bucket" "b" {}',
    "infra/vars.yaml": "env: production",
}

SAMPLE_DOCS = {
    "README.md": "# README content",
    "ARCHITECTURE.md": "# ARCH content",
    "RUNBOOK.md": "# RUNBOOK content",
}


# ---------------------------------------------------------------------------
# Tests for build_index()
# ---------------------------------------------------------------------------

class TestBuildIndex:

    def test_happy_path_contains_all_doc_links(self):
        m = import_module()
        result = m.build_index("myorg", "myrepo", SAMPLE_DOCS, "2024-01-15 10:00 UTC")

        assert "README.md" in result
        assert "ARCHITECTURE.md" in result
        assert "RUNBOOK.md" in result

    def test_happy_path_links_point_to_correct_url(self):
        m = import_module()
        result = m.build_index("myorg", "myrepo", SAMPLE_DOCS, "2024-01-15 10:00 UTC")

        expected_base = (
            f"https://github.com/{FAKE_OUTPUT_REPO_OWNER}/{FAKE_OUTPUT_REPO}"
            "/blob/main/tech-docs/myorg-myrepo/"
        )
        assert expected_base + "README.md" in result
        assert expected_base + "ARCHITECTURE.md" in result
        assert expected_base + "RUNBOOK.md" in result

    def test_happy_path_contains_owner_and_repo(self):
        m = import_module()
        result = m.build_index("acme", "backend", SAMPLE_DOCS, "2024-06-01 00:00 UTC")

        assert "acme/backend" in result

    def test_happy_path_contains_timestamp(self):
        m = import_module()
        timestamp = "2024-03-22 08:30 UTC"
        result = m.build_index("org", "repo", SAMPLE_DOCS, timestamp)

        assert timestamp in result

    def test_happy_path_contains_generated_footer(self):
        m = import_module()
        result = m.build_index("org", "repo", SAMPLE_DOCS, "2024-01-01 00:00 UTC")

        assert "Auto-generated by AI Delivery Bot" in result

    def test_empty_docs_dict_produces_no_doc_links(self):
        m = import_module()
        result = m.build_index("org", "repo", {}, "2024-01-01 00:00 UTC")

        assert "README.md" not in result
        assert "ARCHITECTURE.md" not in result
        # Header and footer should still appear
        assert "Tech Documentation Index" in result

    def test_single_doc_produces_exactly_one_link(self):
        m = import_module()
        result = m.build_index("org", "repo", {"README.md": "content"}, "2024-01-01 00:00 UTC")

        assert result.count("README.md") >= 1
        assert "ARCHITECTURE.md" not in result

    def test_special_characters_in_owner_and_repo(self):
        """Repo/owner names with hyphens are common on GitHub."""
        m = import_module()
        result = m.build_index("my-org", "my-repo", SAMPLE_DOCS, "2024-01-01 00:00 UTC")

        assert "my-org/my-repo" in result
        assert "my-org-my-repo" in result  # path segment in URL

    def test_index_title_format(self):
        m = import_module()
        result = m.build_index("owner", "repo", SAMPLE_DOCS, "2024-01-01 00:00 UTC")

        assert result.startswith("# Tech Documentation Index")

    def test_generated_label_present(self):
        m = import_module()
        result = m.build_index("owner", "repo", SAMPLE_DOCS, "2024-01-01 00:00 UTC")

        assert "**Generated:**" in result


# ---------------------------------------------------------------------------
# Tests for generate_docs()
# ---------------------------------------------------------------------------

class TestGenerateDocs:

    def test_happy_path_calls_get_repo_files_twice(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.return_value = "# content"

        m.generate_docs("myorg", "myrepo", "https://github.com/run/1")

        assert inject_fake_shared.get_repo_files.call_count == 2

    def test_happy_path_first_call_fetches_source_files(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.return_value = "content"

        m.generate_docs("myorg", "myrepo", "https://github.com/run/1")

        first_call_args = inject_fake_shared.get_repo_files.call_args_list[0]
        extensions = first_call_args[0][2]  # positional arg index 2
        assert ".py" in extensions
        assert ".js" in extensions
        assert ".ts" in extensions
        assert ".go" in extensions

    def test_happy_path_second_call_fetches_iac_files(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.return_value = "content"

        m.generate_docs("myorg", "myrepo", "https://github.com/run/1")

        second_call_args = inject_fake_shared.get_repo_files.call_args_list[1]
        extensions = second_call_args[0][2]
        assert ".tf" in extensions
        assert ".yaml" in extensions
        assert ".yml" in extensions

    def test_happy_path_calls_claude_three_times(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.return_value = "content"

        m.generate_docs("myorg", "myrepo", "https://run")

        assert inject_fake_shared.call_claude.call_count == 3

    def test_happy_path_returns_three_docs(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.return_value = "content"

        result = m.generate_docs("myorg", "myrepo", "https://run")

        assert set(result.keys()) == {"README.md", "ARCHITECTURE.md", "RUNBOOK.md"}

    def test_happy_path_doc_content_comes_from_claude(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.side_effect = [
            "# README",
            "# ARCH",
            "# RUNBOOK",
        ]

        result = m.generate_docs("myorg", "myrepo", "https://run")

        assert result["README.md"] == "# README"
        assert result["ARCHITECTURE.md"] == "# ARCH"
        assert result["RUNBOOK.md"] == "# RUNBOOK"

    def test_fmt_no_files_uses_placeholder(self, inject_fake_shared):
        """When no files are found, the prompt should include _No files found_."""
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}

        captured_prompts = []
        def capture_claude(system, user):
            captured_prompts.append(user)
            return "content"

        inject_fake_shared.call_claude.side_effect = capture_claude

        m.generate_docs("myorg", "myrepo", "https://run")

        assert any("_No files found_" in p for p in captured_prompts)

    def test_fmt_truncates_file_content_at_4000_chars(self, inject_fake_shared):
        """File content longer than 4000 chars should be truncated in prompts."""
        long_content = "x" * 8000
        inject_fake_shared.get_repo_files.side_effect = [
            {"src/big.py": long_content},
            {},
        ]

        captured_prompts = []
        def capture_claude(system, user):
            captured_prompts.append(user)
            return "content"

        inject_fake_shared.call_claude.side_effect = capture_claude

        m = import_module()
        m.generate_docs("myorg", "myrepo", "https://run")

        # The full 8000-char string should NOT appear in any prompt
        assert not any("x" * 8000 in p for p in captured_prompts)
        # But the first 4000 chars should appear
        assert any("x" * 4000 in p for p in captured_prompts)

    def test_prompt_includes_owner_and_repo(self, inject_fake_shared):
        inject_fake_shared.get_repo_files.return_value = {}

        captured = []
        def capture_claude(system, user):
            captured.append(user)
            return "content"

        inject_fake_shared.call_claude.side_effect = capture_claude

        m = import_module()
        m.generate_docs("acme-corp", "backend-api", "https://run")

        assert all("acme-corp/backend-api" in p for p in captured)

    def test_call_claude_raises_propagates_exception(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.side_effect = RuntimeError("Claude unavailable")

        with pytest.raises(RuntimeError, match="Claude unavailable"):
            m.generate_docs("myorg", "myrepo", "https://run")

    def test_get_repo_files_raises_propagates_exception(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.side_effect = ConnectionError("GitHub unreachable")

        with pytest.raises(ConnectionError, match="GitHub unreachable"):
            m.generate_docs("myorg", "myrepo", "https://run")

    def test_max_files_limit_passed_to_source_files(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.return_value = "content"

        m.generate_docs("myorg", "myrepo", "https://run")

        first_call_kwargs = inject_fake_shared.get_repo_files.call_args_list[0]
        # max_files passed as keyword or positional
        all_args = list(first_call_kwargs[0]) + list(first_call_kwargs[1].values())
        assert 15 in all_args

    def test_max_files_limit_passed_to_iac_files(self, inject_fake_shared):
        m = import_module()
        inject_fake_shared.get_repo_files.return_value = {}
        inject_fake_shared.call_claude.return_value = "content"

        m.generate_docs("myorg", "myrepo", "https://run")

        second_call = inject_fake_shared.get_repo_files.call_args_list[1]
        all_args = list(second_call[0]) + list(second_call[1].values())
        assert 10 in all_args

    def test_with_actual_files_content_appears_in_prompt(self, inject_fake_shared):
        inject_fake_shared.get_repo_files.side_effect = [
            {"src/app.py": "def main(): pass"},
            {"infra/main.tf": 'resource "aws_s3_bucket" {}'},
        ]

        captured = []
        def capture_claude(system, user):
            captured.append(user)
            return "content"

        inject_fake_shared.call_claude.side_effect = capture_claude

        m = import_module()
        m.generate_docs("org", "repo", "https://run")

        readme_prompt = captured[0]
        assert "src/app.py" in readme_prompt
        assert "def main(): pass" in readme_prompt


# ---------------------------------------------------------------------------
# Tests for __main__ block (happy path)
# -----------